#!/bin/sh

if [ $# == 0 ]; then
    echo "Usage: ./tune-main <BINDIR> <EXECDIR> additional_args_to_irace"
    exit 1
fi

BINDIR=$1
EXECDIR=$2
shift 2

# Working on /tmp should be faster
TMP=\$(mktemp -d -t \${HOSTNAME}-XXXXXXXXXX)
if [ ! -d "\$TMP" ]; then
  echo "cannot create temporary directory" >&2
  exit 1
fi
echo \$TMP/irace-$$.stdout >&2
exec 1> \$TMP/irace-$$.stdout
echo \$TMP/irace-$$.stdout >&2
$BINDIR/irace --exec-dir=\$TMP $*
RET=\$?
# Use command to avoid aliases
command cp --force -R \$TMP/./ $EXECDIR/
rm -rf \$TMP
exit \$RET
